name: weather_app_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.7.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4 
  intl: ^0.19.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.1
  jiffy: ^6.3.1  # Add this line to include the Jiffy package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
